##Univariate One Step Problem

In [62]:
# univariate one step problem
from numpy import array
from keras.preprocessing.sequence import TimeseriesGenerator

# define dataset
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# define generator
n_input = 2
generator = TimeseriesGenerator(series, series, length=n_input, batch_size=1)

# number of samples
print('Samples: %d' % len(generator))

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

Samples: 8
[[1 2]] => [3]
[[2 3]] => [4]
[[3 4]] => [5]
[[4 5]] => [6]
[[5 6]] => [7]
[[6 7]] => [8]
[[7 8]] => [9]
[[8 9]] => [10]


In [63]:
from keras.layers import LSTM
from keras.models import Sequential
from keras.layers import Dense

# define dataset
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# reshape to [10, 1]
n_features = 1
series = series.reshape((len(series), n_features))

# define generator
n_input = 2
generator = TimeseriesGenerator(series, series, length=n_input, batch_size=8)

# define model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_input, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit_generator(generator, steps_per_epoch=1, epochs=500, verbose=0)

# make a one step prediction out of sample
x_input = array([9, 10]).reshape((1, n_input, n_features))
yhat = model.predict(x_input, verbose=0)
print('Predicted:', yhat)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Predicted: [[10.877463]]


In [64]:
# define generator
n_input = 3
generator = TimeseriesGenerator(series, series, length=n_input, batch_size=1)

# number of samples
print('Samples: %d' % len(generator))

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

Samples: 7
[[[1]
  [2]
  [3]]] => [[4]]
[[[2]
  [3]
  [4]]] => [[5]]
[[[3]
  [4]
  [5]]] => [[6]]
[[[4]
  [5]
  [6]]] => [[7]]
[[[5]
  [6]
  [7]]] => [[8]]
[[[6]
  [7]
  [8]]] => [[9]]
[[[7]
  [8]
  [9]]] => [[10]]


In [65]:
# define generator
n_input = 5
generator = TimeseriesGenerator(series, series, length=n_input, batch_size=1)

# number of samples
print('Samples: %d' % len(generator))

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

Samples: 5
[[[1]
  [2]
  [3]
  [4]
  [5]]] => [[6]]
[[[2]
  [3]
  [4]
  [5]
  [6]]] => [[7]]
[[[3]
  [4]
  [5]
  [6]
  [7]]] => [[8]]
[[[4]
  [5]
  [6]
  [7]
  [8]]] => [[9]]
[[[5]
  [6]
  [7]
  [8]
  [9]]] => [[10]]


##Multivariate One Step Problem

In [66]:
# multivariate one step problem
from numpy import hstack

# define dataset
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95, 105])

# reshape series
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2))
print(dataset)

# define generator
n_input = 2
generator = TimeseriesGenerator(dataset, dataset, length=n_input, batch_size=1)

# number of samples
print('Samples: %d' % len(generator))

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

[[ 10  15]
 [ 20  25]
 [ 30  35]
 [ 40  45]
 [ 50  55]
 [ 60  65]
 [ 70  75]
 [ 80  85]
 [ 90  95]
 [100 105]]
Samples: 8
[[[10 15]
  [20 25]]] => [[30 35]]
[[[20 25]
  [30 35]]] => [[40 45]]
[[[30 35]
  [40 45]]] => [[50 55]]
[[[40 45]
  [50 55]]] => [[60 65]]
[[[50 55]
  [60 65]]] => [[70 75]]
[[[60 65]
  [70 75]]] => [[80 85]]
[[[70 75]
  [80 85]]] => [[90 95]]
[[[80 85]
  [90 95]]] => [[100 105]]


In [67]:
# define dataset
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95, 105])

# reshape series
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2))

# define generator
n_features = dataset.shape[1]
n_input = 2
generator = TimeseriesGenerator(dataset, dataset, length=n_input, batch_size=8)

# define model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_input, n_features)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit_generator(generator, steps_per_epoch=1, epochs=500, verbose=0)

# make a one step prediction out of sample
x_input = array([[90, 95], [100, 105]]).reshape((1, n_input, n_features))
yhat = model.predict(x_input, verbose=0)
print('Predicted:', yhat)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Predicted: [[109.9741  115.24936]]


In [68]:
# define generator
n_input = 3
generator = TimeseriesGenerator(dataset, dataset, length=n_input, batch_size=1)

# number of samples
print('Samples: %d' % len(generator))

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

Samples: 7
[[[10 15]
  [20 25]
  [30 35]]] => [[40 45]]
[[[20 25]
  [30 35]
  [40 45]]] => [[50 55]]
[[[30 35]
  [40 45]
  [50 55]]] => [[60 65]]
[[[40 45]
  [50 55]
  [60 65]]] => [[70 75]]
[[[50 55]
  [60 65]
  [70 75]]] => [[80 85]]
[[[60 65]
  [70 75]
  [80 85]]] => [[90 95]]
[[[70 75]
  [80 85]
  [90 95]]] => [[100 105]]


In [69]:
# define generator
n_input = 5
generator = TimeseriesGenerator(dataset, dataset, length=n_input, batch_size=1)

# number of samples
print('Samples: %d' % len(generator))

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

Samples: 5
[[[10 15]
  [20 25]
  [30 35]
  [40 45]
  [50 55]]] => [[60 65]]
[[[20 25]
  [30 35]
  [40 45]
  [50 55]
  [60 65]]] => [[70 75]]
[[[30 35]
  [40 45]
  [50 55]
  [60 65]
  [70 75]]] => [[80 85]]
[[[40 45]
  [50 55]
  [60 65]
  [70 75]
  [80 85]]] => [[90 95]]
[[[50 55]
  [60 65]
  [70 75]
  [80 85]
  [90 95]]] => [[100 105]]


##Multivariate One Step Problem

In [70]:
# multivariate one step problem

# define dataset
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95, 105])
out_seq = array([25, 45, 65, 85, 105, 125, 145, 165, 185, 205])

# reshape series
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2))
print(dataset)

# define generator
n_input = 1
generator = TimeseriesGenerator(dataset, out_seq, length=n_input, batch_size=1)

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

[[ 10  15]
 [ 20  25]
 [ 30  35]
 [ 40  45]
 [ 50  55]
 [ 60  65]
 [ 70  75]
 [ 80  85]
 [ 90  95]
 [100 105]]
[[[10 15]]] => [[45]]
[[[20 25]]] => [[65]]
[[[30 35]]] => [[85]]
[[[40 45]]] => [[105]]
[[[50 55]]] => [[125]]
[[[60 65]]] => [[145]]
[[[70 75]]] => [[165]]
[[[80 85]]] => [[185]]
[[[90 95]]] => [[205]]


In [71]:
# multivariate one step problem
from numpy import insert

# define dataset
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95, 105])
out_seq = array([25, 45, 65, 85, 105, 125, 145, 165, 185, 205])

# reshape series
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2))
print(dataset)

# shift the target sample by one step
out_seq = insert(out_seq, 0, 0)

# define generator
n_input = 1
generator = TimeseriesGenerator(dataset, out_seq[:-1], length=n_input, batch_size=1)

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

[[ 10  15]
 [ 20  25]
 [ 30  35]
 [ 40  45]
 [ 50  55]
 [ 60  65]
 [ 70  75]
 [ 80  85]
 [ 90  95]
 [100 105]]
[[[10 15]]] => [25]
[[[20 25]]] => [45]
[[[30 35]]] => [65]
[[[40 45]]] => [85]
[[[50 55]]] => [105]
[[[60 65]]] => [125]
[[[70 75]]] => [145]
[[[80 85]]] => [165]
[[[90 95]]] => [185]


##Univariate Multi-Step Problem

In [72]:
# univariate multi-step problem

# define dataset
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
target = array([[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,10],[10,11]])

# define generator
n_input = 2
generator = TimeseriesGenerator(series, target, length=n_input, batch_size=1)

# print each sample
for i in range(len(generator)):
	x, y = generator[i]
	print('%s => %s' % (x, y))

[[1 2]] => [[3 4]]
[[2 3]] => [[4 5]]
[[3 4]] => [[5 6]]
[[4 5]] => [[6 7]]
[[5 6]] => [[7 8]]
[[6 7]] => [[8 9]]
[[7 8]] => [[ 9 10]]
[[8 9]] => [[10 11]]
